services:
  postgres:
    image: postgres:16
    container_name: hack4good-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hack4good
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d hack4good"]
      interval: 10s
      timeout: 5s
      retries: 5  

volumes:
  pgdata:
